import { useEffect, useState } from 'react'
import { getDashboardClients } from '../services/dashboard'
import type { ClientStatus, DashboardClient } from '../types/dashboard'
import { formatCedula } from '../utils/cedula'

export function ClientDirectory({ onSelectClient }: { onSelectClient: (cedula: string) => void }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<ClientStatus>('all'); const [rows, setRows] = useState<DashboardClient[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; setLoading(true); const timer = window.setTimeout(() => { getDashboardClients(search, status).then((next) => active && setRows(next)).catch((cause: unknown) => active && setError(cause instanceof Error ? cause.message : 'No se pudo cargar clientes.')).finally(() => active && setLoading(false)) }, 250); return () => { active = false; window.clearTimeout(timer) } }, [search, status])
  return <section className="directory-page"><div className="section-heading"><div><span className="eyebrow">Base de datos</span><h2>Clientes</h2></div></div><div className="directory-filters"><input aria-label="Buscar cliente" value={search} placeholder="Buscar por nombre o cédula" onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filtrar clientes" value={status} onChange={(event) => setStatus(event.target.value as ClientStatus)}><option value="all">Todos</option><option value="empty">Sin compras</option><option value="active">Activos (1–9)</option><option value="ready">Beneficio disponible</option></select></div>{error && <p className="status error">{error}</p>}<div className="directory-table" aria-busy={loading}><div className="directory-header"><span>Cliente</span><span>Progreso</span><span /></div>{rows.length === 0 && !loading ? <p className="empty-state">No hay clientes que coincidan.</p> : rows.map((client) => <button className="directory-row" key={client.id} onClick={() => onSelectClient(client.cedula)}><span><strong>{client.name}</strong><small>V-{formatCedula(client.cedula)}</small></span><b className={client.purchase_count === 10 ? 'ready' : ''}>{client.purchase_count}/10</b><span>Ver ›</span></button>)}</div></section>
}
